# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('definition', models.TextField(blank=True)),
                ('language', models.CharField(max_length=25)),
                ('antonyms', models.ManyToManyField(blank=True, related_name='_words_antonyms_+', to='dictionary.Words')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_words_synonyms_+', to='dictionary.Words')),
                ('translaions', models.ManyToManyField(blank=True, related_name='_words_translaions_+', to='dictionary.Words')),
            ],
        ),
    ]
