# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='translaions',
        ),
        migrations.AddField(
            model_name='words',
            name='translation',
            field=models.ManyToManyField(blank=True, related_name='_words_translation_+', to='dictionary.Words'),
        ),
        migrations.AlterField(
            model_name='words',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='words',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('ru', 'russian'), ('kz', 'kazakh')], max_length=3),
        ),
        migrations.AlterField(
            model_name='words',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
